services:
  soc-api-transaction:
    build:
      context: .
      target: production
    container_name: soc-api-transaction
    image: transaction-service:latest
    ports:
      - "3003:3000"
#    env_file:
#      - .env
    environment:
      - MARIADB_HOST=${MARIADB_HOST}
      - MARIADB_PORT=${MARIADB_PORT}
      - MARIADB_USERNAME=${MARIADB_USERNAME}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_NAME=${MARIADB_NAME}
      - MARIADB_NAME_PROFILE=${MARIADB_NAME_PROFILE}
      - MARIADB_NAME_PRODUCT=${MARIADB_NAME_PRODUCT}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - APP_URL=${APP_URL}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL=${EMAIL}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_FROM=${EMAIL_FROM}
      - EMAIL_ADMIN=${EMAIL_ADMIN}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - soc-network

networks:
  soc-network:
    external: true